const IMAGES = {
    IMAGES_LOAD: 'IMAGES_LOAD',
    IMAGES_LOAD_SUCCESS: 'IMAGES_LOAD_SUCCESS',
    IMAGES_LOAD_FAIL: 'IMAGES_LOAD_FAIL',
};

const STATS = {
    STATS_LOAD: 'STATS_LOAD',
    STATS_LOAD_SUCCESS: 'STATS_LOAD_SUCCESS',
    STATS_LOAD_FAIL: 'STATS_LOAD_FAIL',
};

export { IMAGES, STATS };
